### ISSUE TITLE
Incorrect AST is generated with struct calls inside of typedef'd structs

### ISSUE THREAD

**Issue by d0c-s4vage** [d0c-s4vage/py010parser#35]
## Problem

In the code below, a struct call statement exists to declare the variable `value` inside of a typedef'd struct:

```c
typedef struct (int size, int type) {
} EncodedValue <read=EncodedValueRead, optimize=false>;

typedef struct {
    local int value_type = 0;
    local int value_arg = 0;
    EncodedValue value(value_arg, value_type);
} TEST;
TEST test1;
```

The generated AST shows that instead of a `StructCallTypeDecl` node in the AST existing, a `FuncDecl` node exists instead.

```
  Typedef: TEST, [], ['typedef']
    TypeDecl: TEST, []
      Struct: None
        Decl: value_type, ['local'], [], []
          TypeDecl: value_type, ['local']
            IdentifierType: ['int']
          Constant: int, 0
        Decl: value_arg, ['local'], [], []
          TypeDecl: value_arg, ['local']
            IdentifierType: ['int']
          Constant: int, 0
        Decl: value, [], [], []
          FuncDecl: 
            ParamList: 
              ID: value_arg
              ID: value_type
            TypeDecl: value, []
              IdentifierType: ['EncodedValue']
  Decl: test1, [], [], []
    TypeDecl: test1, []
      IdentifierType: ['TEST']
```

Conversely, if we change the struct to *not* be a typedef'd struct, everything works as expected:

```c
typedef struct (int size, int type) {
} EncodedValue <read=EncodedValueRead, optimize=false>;

struct {
    local int value_type = 0;
    local int value_arg = 0;
    EncodedValue value(value_arg, value_type);
} TEST;
```

with the resulting, relevant node from the AST being:

```
  Decl: TEST, [], [], []
    TypeDecl: TEST, []
      Struct: None
        Decl: value_type, ['local'], [], []
          TypeDecl: value_type, ['local']
            IdentifierType: ['int']
          Constant: int, 0
        Decl: value_arg, ['local'], [], []
          TypeDecl: value_arg, ['local']
            IdentifierType: ['int']
          Constant: int, 0
        Decl: value, [], [], []
          StructCallTypeDecl: value, []
            IdentifierType: ['EncodedValue']
```
